/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package manager;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import main.Controller;

/**
 *
 * @author Riky Setiawan 2013730041 , Sukamto 2013730026
 */
public class EditPaketKursusForm extends javax.swing.JFrame {

    Statement statement;
    Controller cont;
    String idPaket;
    String namaPaket;
    String jenisAlatMusik;
    String biaya;
    
    /**
     * Creates new form EditPaketKursusForm
     */
    public EditPaketKursusForm(Controller cont) {
        this.cont = cont;
        statement = cont.getStatement();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idPaketLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        namaPaketField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        biayaField = new javax.swing.JTextField();
        jenisAlatMusikBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Paket");

        idPaketLabel.setText("idPaket");

        jLabel7.setText(":");

        jLabel8.setText(":");

        jLabel3.setText("Nama Paket");

        jLabel10.setText(":");

        jLabel5.setText("Jenis Alat Musik");

        jLabel6.setText("Biaya");

        jLabel11.setText(":");

        saveButton.setText("Save Changes");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jenisAlatMusikBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Alat Musik", "Gitar", "Piano", "Drum", "Bass", "Saxophone", "Gamelan", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(75, 75, 75)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel10)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(biayaField)
                            .addComponent(jenisAlatMusikBox, 0, 145, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(saveButton)
                        .addGap(49, 49, 49)
                        .addComponent(cancelButton)))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3))
                    .addGap(43, 43, 43)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(idPaketLabel)
                        .addComponent(namaPaketField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(78, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel5)
                    .addComponent(jenisAlatMusikBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel6)
                    .addComponent(biayaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addGap(40, 40, 40))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel7)
                        .addComponent(idPaketLabel))
                    .addGap(9, 9, 9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(namaPaketField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addContainerGap(136, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        boolean isChanges = false;
        String newNama = namaPaketField.getText().trim();
        String query;
        ResultSet rs;
        if(!newNama.equals(namaPaket)){
            isChanges = true;
            query = String.format("UPDATE PaketKursus SET namaPaket = '%s' where idPaket ='%s' " , newNama , idPaket);
            try {
                statement.execute(query);
            } catch (SQLException ex) {
                Logger.getLogger(EditDataPegawaiForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        String newAlatMusik = jenisAlatMusikBox.getSelectedItem()+"";
        if(!newAlatMusik.equals(jenisAlatMusik)){
            isChanges = true;
            query = String.format("UPDATE PaketKursus SET jenisAlatMusik = '%s' where idPaket ='%s' " , newAlatMusik , idPaket);
            try {
                statement.execute(query);
            } catch (SQLException ex) {
                Logger.getLogger(EditDataPegawaiForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        String newBiaya = biayaField.getText().trim();
        if(!newBiaya.equals(biaya)){
            isChanges = true;
            query = String.format("UPDATE PaketKursus SET biaya = '%s' where idPaket ='%s' " , newBiaya , idPaket);
            try {
                statement.execute(query);
            } catch (SQLException ex) {
                Logger.getLogger(EditDataPegawaiForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(isChanges){
            JOptionPane.showMessageDialog(null, "Changes saved.");
        }
        this.setVisible(false);
        this.cont.getPaketKursus().setTabel();
        this.cont.getPaketKursus().setVisible(true);
    }//GEN-LAST:event_saveButtonActionPerformed

    public void setData(String idPaket){
        String query = String.format("select * from PaketKursus where idPaket = '%s'",idPaket);
        try {
            ResultSet rs = statement.executeQuery(query);
            rs.next();
            this.idPaket = idPaket;
            this.idPaketLabel.setText(idPaket);
            namaPaket = rs.getString("namaPaket");
            this.namaPaketField.setText(namaPaket);
            String idAlat = rs.getString("jenisAlatMusik");
            biaya = rs.getString("biaya");
            this.biayaField.setText(biaya);
            ResultSet rsAlat = statement.executeQuery(String.format("select namaAlat from AlatMusik where idAlat = '%s'",idAlat));
            rsAlat.next();
            jenisAlatMusik = rsAlat.getString("namaAlat");
            this.jenisAlatMusikBox.setSelectedItem(jenisAlatMusik.trim());
        } catch (SQLException ex) {
            Logger.getLogger(EditDataPegawaiForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.cont.getPaketKursus().setVisible(true);
        this.cont.getPaketKursus().setTabel();
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField biayaField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel idPaketLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox jenisAlatMusikBox;
    private javax.swing.JTextField namaPaketField;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
