/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package receptionist;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import main.Controller;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author Riky Setiawan 2013730041 , Sukamto 2013730026
 */
public class DaftarUlangForm extends javax.swing.JFrame {

    Controller cont;
    Statement statement;
    String idSiswa;
    String idPaket;
    String namaPaket;
    
    /**
     * Creates new form DaftarUlangForm
     */
    public DaftarUlangForm(Controller cont) {
        this.cont = cont;
        statement = this.cont.getStatement();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        backButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        idSiswaField = new javax.swing.JTextField();
        idPegawaiLabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        labelHarga = new javax.swing.JLabel();
        jadwalBox = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        daftarButton = new javax.swing.JButton();
        paketLabel = new javax.swing.JLabel();
        checkButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Melodia Music Lesson");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("Log Out");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("ID Siswa : ");

        idPegawaiLabel.setText(" ");

        jLabel15.setText("Biaya :");

        labelHarga.setText(" ");

        jadwalBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jadwalBoxActionPerformed(evt);
            }
        });

        jLabel17.setText("Jadwal :");

        jLabel11.setText("Paket : ");

        jLabel10.setText("ID Receptionist : ");

        daftarButton.setText("Daftar");
        daftarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarButtonActionPerformed(evt);
            }
        });

        paketLabel.setText(" ");

        checkButton.setText("Check");
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(33, 33, 33)
                                .addComponent(logoutButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(checkButton))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(idPegawaiLabel)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(paketLabel)
                                                .addGap(33, 33, 33)
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelHarga))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel17)
                                            .addGap(53, 53, 53)
                                            .addComponent(jadwalBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addComponent(daftarButton)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel9)
                    .addGap(42, 42, 42)
                    .addComponent(idSiswaField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(163, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoutButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(backButton)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(checkButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(idPegawaiLabel))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHarga)
                    .addComponent(jLabel11)
                    .addComponent(paketLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jadwalBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addComponent(daftarButton)
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(idSiswaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(194, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.cont.getHomepageRec().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        this.cont.getLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void jadwalBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jadwalBoxActionPerformed

    }//GEN-LAST:event_jadwalBoxActionPerformed

    public void clear(){
        idSiswaField.setText("");
        idPegawaiLabel.setText(" ");
        paketLabel.setText(" ");
        labelHarga.setText(" ");
    }
    
    private void daftarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarButtonActionPerformed
        try {
            
            int totalBiaya = Integer.parseInt(labelHarga.getText());
            String tglDaftar = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
            String query = String.format("Select * from Siswa where idSiswa = '%s'",idSiswa);
            ResultSet rs = statement.executeQuery(query);
            rs.next();
            int sisaPertemuan = rs.getInt("sisaPertemuan");
            query = String.format("Select namaLengkap from Siswa where idSiswa = '%s'",idSiswa);
            rs = statement.executeQuery(query);
            rs.next();
            String namaLengkap = rs.getString("namaLengkap");
            query = String.format("UPDATE Siswa SET sisaPertemuan = '%d' where idSiswa = '%s'",sisaPertemuan+5,idSiswa);
            statement.execute(query);
            String[] split = (jadwalBox.getSelectedItem()+"").split(",");
            String[] split2 = split[1].split(" - ");
            String hari = split[0].trim();
            String jamMulai = split2[0].trim();
            String jamBerakhir = split2[0].trim();
            query = String.format("select idJadwal from Jadwal where idPaket = '%s' AND jamMulai = '%s'",idPaket,jamMulai);
            rs = statement.executeQuery(query);
            rs.next();
            String idJadwal = rs.getString("idJadwal");
            query = String.format("UPDATE Siswa SET tglDaftar = '%s' where idSiswa = '%s'",tglDaftar,idSiswa);
            statement.execute(query);
            query = String.format("UPDATE Siswa SET idJadwal = '%s' where idSiswa = '%s'",idJadwal,idSiswa);
            statement.execute(query);
            
            String timeStamp = new SimpleDateFormat("HH:mm:ss").format(Calendar.getInstance().getTime());
            query = String.format("INSERT INTO Transaksi values ('%s','%s','%s','%s','%s','%s','%s')", idSiswa, namaLengkap, this.cont.getIdPegawai(), idPaket, totalBiaya, tglDaftar, timeStamp);
            statement.execute(query);
            query = String.format("select idTransaksi from Transaksi");
            rs = statement.executeQuery(query);
            String idTransaksi = "";
            while(rs.next()){
                idTransaksi = rs.getString("idTransaksi");
            }
            String namaPegawai = this.cont.getNamaPegawai();
            this.cont.getFormTransaksi().setTransaksi(idTransaksi, tglDaftar, timeStamp, idSiswa,namaLengkap,totalBiaya,idPaket,namaPegawai);
            this.cont.getFormTransaksi().setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(PendaftaranSiswaForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_daftarButtonActionPerformed

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
        try{
            jadwalBox.removeAllItems();
            idSiswa = idSiswaField.getText();
            String query = String.format("select idPaket from Siswa where idSiswa = '%s'",idSiswa);
            ResultSet rs = statement.executeQuery(query);
            rs.next();
            idPaket = rs.getString("idPaket");
            query = String.format("select namaPaket from PaketKursus where idPaket ='%s'",idPaket);
            rs = statement.executeQuery(query);
            rs.next();
            namaPaket = rs.getString("namaPaket");
            this.paketLabel.setText(namaPaket);
            this.idPegawaiLabel.setText(this.cont.getIdPegawai());
            query = String.format("select biaya from PaketKursus where idPaket ='%s'",idPaket);
            rs = statement.executeQuery(query);
            rs.next();
            String biaya = rs.getString("biaya");
            labelHarga.setText(biaya);
            query = String.format("select * from Jadwal where idPaket = '%s'", idPaket);
            rs = statement.executeQuery(query);
            int i = 0;
            while (rs.next()) {
                jadwalBox.addItem(rs.getString("hari") + ", " + rs.getString("jamMulai") + " - " + rs.getString("jamAkhir"));
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(PendaftaranSiswaForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_checkButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton checkButton;
    private javax.swing.JButton daftarButton;
    private javax.swing.JLabel idPegawaiLabel;
    private javax.swing.JTextField idSiswaField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox jadwalBox;
    private javax.swing.JLabel labelHarga;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel paketLabel;
    // End of variables declaration//GEN-END:variables
}
